#!/usr/bin/env python3
"""快速生成演示周报（使用预设数据）"""

import json
import sys
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent))

from core.editor import WeeklyEditor
from core.sender import EmailSender

# 使用之前保存的数据
output_dir = Path("/home/gem/workspace/agent/workspace/weekly_output")
json_files = sorted(output_dir.glob("weekly_*.json"))

if json_files:
    with open(json_files[-1], "r") as f:
        data = json.load(f)
    
    # 提取内容
    all_summaries = []
    for category in ['open_source', 'papers', 'industry_news', 'top_highlights']:
        for item in data.get('weekly_report', {}).get(category, []):
            item['category'] = category
            all_summaries.append(item)
    
    # 转换为 editor 格式
    items = []
    for s in all_summaries:
        items.append({
            "title": s.get('title', ''),
            "source": s.get('source', 'unknown'),
            "url": s.get('url', '#'),
            "raw_text": s.get('raw_text', s.get('what_it_is', '')),
            "domain_tags": s.get('domain_tags', []),
            "final_score": len(s.get('domain_tags', [])) * 3 + 5,
            "meta": s.get('meta', {})
        })
    
    print(f"📊 内容数：{len(items)} 条")
    
    cv_count = sum(1 for i in items if any(t in i.get('domain_tags', []) for t in ['CV', 'OCR', 'Medical Imaging', 'Multimodal']))
    print(f"   CV/OCR 相关：{cv_count} 条")
    
    # 生成周报
    issue_number = data.get('weekly_report', {}).get('issue_number', 1)
    time_range = data.get('weekly_report', {}).get('time_range', '最近 7 天')
    
    print(f"\n✍️ 生成周报（第 {issue_number} 期）...")
    editor = WeeklyEditor()
    result = editor.generate(items, issue_number)
    
    if not result.get('success'):
        print(f"❌ 生成失败：{result.get('error')}")
        sys.exit(1)
    
    markdown = result.get('markdown', '')
    print(f"   ✅ 周报已生成（{len(markdown)} 字符）")
    
    # 渲染 HTML
    print("\n🎨 渲染 HTML...")
    
    import re
    html_body = markdown
    html_body = re.sub(r'^###### (.+)$', r'<h6>\1</h6>', html_body, flags=re.MULTILINE)
    html_body = re.sub(r'^##### (.+)$', r'<h5>\1</h5>', html_body, flags=re.MULTILINE)
    html_body = re.sub(r'^#### (.+)$', r'<h4>\1</h4>', html_body, flags=re.MULTILINE)
    html_body = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html_body, flags=re.MULTILINE)
    html_body = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html_body, flags=re.MULTILINE)
    html_body = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html_body, flags=re.MULTILINE)
    html_body = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html_body)
    html_body = re.sub(r'\[(.+?)\]\((.+?)\)', r'<a href="\2" target="_blank">\1</a>', html_body)
    
    lines = html_body.split('\n')
    processed = []
    in_list = False
    for line in lines:
        if line.startswith('- ') or line.startswith('* '):
            if not in_list:
                processed.append('<ul>')
                in_list = True
            processed.append(f'<li>{line[2:]}</li>')
        else:
            if in_list:
                processed.append('</ul>')
                in_list = False
            if line.strip():
                processed.append(f'<p>{line}</p>')
    if in_list:
        processed.append('</ul>')
    
    html_body = '\n'.join(processed)
    now = datetime.now()
    
    html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>AI/CV Weekly - 第{issue_number}期</title>
    <style>
        body {{ font-family: -apple-system, sans-serif; line-height: 1.8; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 20px; }}
        .container {{ max-width: 800px; margin: 0 auto; }}
        header {{ background: rgba(255,255,255,0.95); padding: 32px; border-radius: 16px; margin-bottom: 24px; }}
        header h1 {{ background: linear-gradient(135deg, #667eea, #764ba2); -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-size: 32px; }}
        .content {{ background: white; padding: 40px; border-radius: 16px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }}
        h2 {{ border-bottom: 3px solid #667eea; padding-bottom: 12px; margin-top: 32px; }}
        a {{ color: #667eea; }}
        .footer {{ text-align: center; padding: 32px; color: rgba(255,255,255,0.8); background: rgba(255,255,255,0.1); border-radius: 16px; margin-top: 24px; }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🦞 AI/CV Weekly</h1>
            <p>第 {issue_number} 期 | {now.strftime("%Y-%m-%d")}</p>
            <p>时间范围：{time_range}</p>
        </header>
        <div class="content">{html_body}</div>
        <div class="footer"><p>Generated by AI/CV Weekly - 主编模式</p></div>
    </div>
</body>
</html>"""
    
    # 保存
    output_dir = Path(__file__).parent / "output"
    output_dir.mkdir(exist_ok=True)
    timestamp = now.strftime("%Y%m%d_%H%M%S")
    html_path = output_dir / f"weekly_{timestamp}.html"
    md_path = output_dir / f"weekly_{timestamp}.md"
    
    with open(html_path, "w") as f:
        f.write(html)
    with open(md_path, "w") as f:
        f.write(markdown)
    
    print(f"   HTML 长度：{len(html)}")
    print(f"   已保存：{html_path}")
    
    # 发送邮件
    print("\n📧 发送邮件...")
    sender = EmailSender()
    subject = f"🦞 AI/CV Weekly - 第{issue_number}期（主编模式）"
    success = sender.send(subject, html, markdown[:1000] + "...")
    
    if success:
        print("   ✅ 邮件已发送!")
        print("\n✅ 完成!")
    else:
        print("   ❌ 邮件发送失败")
        sys.exit(1)

else:
    print("❌ 未找到数据文件")
    sys.exit(1)
